import type { Item } from "@/types";

export const demoItems: Item[] = [
  {
    id: "prompt-product-brief",
    type: "prompt",
    title: "Product Brief Builder",
    content:
      "Turn these rough notes into a concise product brief with problem, audience, goals, scope, risks, and launch checklist: {{notes}}",
    variables: ["notes"],
    tags: ["product", "planning", "prompt"],
    categoryId: "workflow",
    isPinned: true,
    copyCount: 18,
    useCount: 12,
    createdAt: "2026-04-20T09:00:00.000Z",
    updatedAt: "2026-04-28T10:15:00.000Z",
  },
  {
    id: "note-rag-pipeline",
    type: "note",
    title: "RAG Pipeline Notes",
    content:
      "Use asynchronous ingestion for large files. Store document status, chunk count, and source excerpts so chat answers can cite where each answer came from.",
    variables: [],
    tags: ["rag", "architecture", "supabase"],
    categoryId: "architecture",
    isPinned: true,
    copyCount: 6,
    useCount: 9,
    createdAt: "2026-04-21T11:30:00.000Z",
    updatedAt: "2026-04-27T14:40:00.000Z",
  },
  {
    id: "link-pgvector",
    type: "link",
    title: "Supabase Vector Columns",
    content: "Reference for pgvector setup, vector dimensions, and similarity search in Supabase.",
    url: "https://supabase.com/docs/guides/ai/vector-columns",
    variables: [],
    tags: ["supabase", "pgvector", "reference"],
    categoryId: "reference",
    isPinned: false,
    copyCount: 11,
    useCount: 5,
    createdAt: "2026-04-22T08:45:00.000Z",
    updatedAt: "2026-04-26T13:20:00.000Z",
  },
  {
    id: "command-large-files",
    type: "command",
    title: "Find Large Files",
    content: "Lists files larger than 100 MB under the current directory.",
    command: "Get-ChildItem -Recurse -File | Where-Object { $_.Length -gt 100MB }",
    variables: [],
    tags: ["powershell", "maintenance"],
    categoryId: "commands",
    isPinned: false,
    copyCount: 7,
    useCount: 4,
    createdAt: "2026-04-23T16:10:00.000Z",
    updatedAt: "2026-04-25T09:05:00.000Z",
  },
  {
    id: "snippet-sse-reader",
    type: "snippet",
    title: "Streaming Response Reader",
    content:
      "const reader = response.body?.getReader();\nconst decoder = new TextDecoder();\nwhile (reader) {\n  const { value, done } = await reader.read();\n  if (done) break;\n  buffer += decoder.decode(value, { stream: true });\n}",
    variables: [],
    tags: ["typescript", "streaming", "nextjs"],
    categoryId: "snippets",
    isPinned: false,
    copyCount: 15,
    useCount: 10,
    createdAt: "2026-04-24T12:00:00.000Z",
    updatedAt: "2026-04-28T08:25:00.000Z",
  },
  {
    id: "prompt-review",
    type: "prompt",
    title: "Code Review Lens",
    content:
      "Review this diff for correctness, edge cases, missing tests, security risks, and maintainability. Lead with actionable findings: {{diff}}",
    variables: ["diff"],
    tags: ["review", "engineering"],
    categoryId: "workflow",
    isPinned: false,
    copyCount: 23,
    useCount: 16,
    createdAt: "2026-04-25T07:35:00.000Z",
    updatedAt: "2026-04-28T11:00:00.000Z",
  },
];
