import type { Item } from "@/types";

export const demoItems: Item[] = [
  {
    id: "prompt-001",
    type: "prompt",
    title: "Product Requirements Draft",
    content:
      "Act as a senior product manager. Turn the following messy notes into a concise PRD with goals, non-goals, user stories, risks, and launch criteria: {{notes}}",
    tags: ["product", "planning", "rewrite"],
    categoryId: "workflows",
    isPinned: true,
    copyCount: 18,
    useCount: 12,
    createdAt: "2026-04-22T08:30:00.000Z",
    updatedAt: "2026-04-28T11:15:00.000Z",
  },
  {
    id: "command-001",
    type: "command",
    title: "Find Large Files",
    content: "Lists files larger than 100 MB in the current project tree.",
    command: "Get-ChildItem -Recurse -File | Where-Object { $_.Length -gt 100MB }",
    tags: ["powershell", "maintenance"],
    categoryId: "commands",
    isPinned: false,
    copyCount: 7,
    useCount: 5,
    createdAt: "2026-04-20T14:10:00.000Z",
    updatedAt: "2026-04-27T09:05:00.000Z",
  },
  {
    id: "note-001",
    type: "note",
    title: "RAG Ingestion Guardrails",
    content:
      "Keep ingestion asynchronous for large files, store document status, poll from the client, and preserve source excerpts for citations.",
    tags: ["rag", "architecture", "supabase"],
    categoryId: "architecture",
    isPinned: true,
    copyCount: 4,
    useCount: 9,
    createdAt: "2026-04-19T16:42:00.000Z",
    updatedAt: "2026-04-26T18:20:00.000Z",
  },
  {
    id: "link-001",
    type: "link",
    title: "Supabase pgvector Notes",
    content: "Reference notes for vector search setup, indexes, and embedding dimensions.",
    url: "https://supabase.com/docs/guides/ai/vector-columns",
    tags: ["supabase", "pgvector"],
    categoryId: "references",
    isPinned: false,
    copyCount: 11,
    useCount: 6,
    createdAt: "2026-04-17T07:50:00.000Z",
    updatedAt: "2026-04-25T10:12:00.000Z",
  },
  {
    id: "snippet-001",
    type: "snippet",
    title: "SSE Reader Loop",
    content:
      "const reader = response.body?.getReader();\nconst decoder = new TextDecoder();\nwhile (reader) {\n  const { value, done } = await reader.read();\n  if (done) break;\n  buffer += decoder.decode(value, { stream: true });\n}",
    tags: ["nextjs", "streaming", "typescript"],
    categoryId: "snippets",
    isPinned: false,
    copyCount: 15,
    useCount: 10,
    createdAt: "2026-04-16T13:25:00.000Z",
    updatedAt: "2026-04-24T15:30:00.000Z",
  },
  {
    id: "prompt-002",
    type: "prompt",
    title: "Code Review Lens",
    content:
      "Review this diff for correctness, edge cases, missing tests, security risks, and maintainability. Lead with actionable findings: {{diff}}",
    tags: ["review", "engineering"],
    categoryId: "workflows",
    isPinned: false,
    copyCount: 23,
    useCount: 17,
    createdAt: "2026-04-15T09:00:00.000Z",
    updatedAt: "2026-04-23T12:45:00.000Z",
  },
];
